name = "orcun/contract"
version = "0.0.0"
compiler = "v1.1.22"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'orcun/contract'"

[repository]
user = "orcun"
project = "contract"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.5.0"
source = "github"

[config]
